"""
InsightGenerator — the public interface of the AI layer.

Orchestrates PromptBuilder + LLMClient in a single ``generate()`` call
and returns a fully populated ``InsightReport``.

Pipeline position
-----------------
  Ingestion → Cleaning → Analysis → **AI Insights** → Output

Usage
-----
    from ai.insight_generator import InsightGenerator

    generator = InsightGenerator()
    report    = generator.generate(analysis_result, template="full_report")
    print(report.to_markdown())

Dry-run mode
------------
Pass ``dry_run=True`` to skip the API call entirely and return a
placeholder report.  Useful for testing the full pipeline locally
without consuming tokens or needing a real API key.

    generator = InsightGenerator(dry_run=True)
    report    = generator.generate(result)
"""

import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from ai.llm_client import LLMClient, LLMClientError
from ai.prompt_builder import PromptBuilder, PromptPayload
from analysis.insight_builder import AnalysisResult


# ── InsightReport ─────────────────────────────────────────────────────────────

@dataclass
class InsightReport:
    """The complete output of one AI insight generation run.

    This is the final product of the entire pipeline.  It holds the raw
    AI-generated text plus all the metadata needed to audit, store, and
    display the result.

    Attributes
    ----------
    insights_text : str
        The full text generated by the LLM.
    template_used : str
        Which prompt template was used (e.g. ``"full_report"``).
    model : str
        The model that produced this report.
    prompt_tokens : int
    completion_tokens : int
    total_tokens : int
    latency_ms : float
        API round-trip time in milliseconds.
    generated_at : datetime
    analysis_period : dict
        ``{"from": "YYYY-MM-DD", "to": "YYYY-MM-DD"}`` from the analysis.
    row_count : int
        Number of sales records that were analysed.
    was_truncated : bool
        True if the model hit the ``max_tokens`` limit before finishing.
    is_dry_run : bool
        True if this report was generated without a real API call.
    """

    insights_text:     str
    template_used:     str            = "full_report"
    model:             str            = ""
    prompt_tokens:     int            = 0
    completion_tokens: int            = 0
    total_tokens:      int            = 0
    latency_ms:        float          = 0.0
    generated_at:      datetime       = field(default_factory=datetime.now)
    analysis_period:   dict           = field(default_factory=dict)
    row_count:         int            = 0
    was_truncated:     bool           = False
    is_dry_run:        bool           = False

    # ------------------------------------------------------------------ #
    # Output formats                                                      #
    # ------------------------------------------------------------------ #

    def to_markdown(self) -> str:
        """Format the report as a Markdown document.

        Suitable for saving to a .md file or rendering in the Streamlit UI.
        """
        period_str = (
            f"{self.analysis_period.get('from', 'N/A')} → "
            f"{self.analysis_period.get('to', 'N/A')}"
        )
        dry_run_note = "  *(dry run — no real API call was made)*\n" if self.is_dry_run else ""
        truncation_note = (
            "\n> ⚠️ **Note:** This response was truncated — consider increasing `max_tokens`.\n"
            if self.was_truncated else ""
        )

        return (
            f"# Sales Insights Report\n\n"
            f"{dry_run_note}"
            f"**Period:** {period_str}  \n"
            f"**Orders analysed:** {self.row_count:,}  \n"
            f"**Template:** {self.template_used}  \n"
            f"**Model:** {self.model}  \n"
            f"**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M')}  \n"
            f"**Tokens:** {self.prompt_tokens:,} prompt + "
            f"{self.completion_tokens:,} completion = {self.total_tokens:,} total  \n"
            f"**Latency:** {self.latency_ms:.0f} ms  \n"
            f"{truncation_note}\n"
            f"---\n\n"
            f"{self.insights_text}\n"
        )

    def to_dict(self) -> dict:
        """Serialise to a JSON-safe dictionary."""
        return {
            "generated_at":     self.generated_at.isoformat(),
            "analysis_period":  self.analysis_period,
            "row_count":        self.row_count,
            "template_used":    self.template_used,
            "model":            self.model,
            "prompt_tokens":    self.prompt_tokens,
            "completion_tokens":self.completion_tokens,
            "total_tokens":     self.total_tokens,
            "latency_ms":       self.latency_ms,
            "was_truncated":    self.was_truncated,
            "is_dry_run":       self.is_dry_run,
            "insights_text":    self.insights_text,
        }

    def to_json(self, path: Optional[str] = None) -> str:
        """Serialise to JSON string and optionally write to a file."""
        json_str = json.dumps(self.to_dict(), indent=2)
        if path:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(json_str)
        return json_str

    def print_cli(self) -> None:
        """Print a clean CLI-formatted version of the report."""
        divider = "═" * 64
        period  = (
            f"{self.analysis_period.get('from', '?')} → "
            f"{self.analysis_period.get('to', '?')}"
        )
        header = [
            f"\n{divider}",
            f"  AI SALES INSIGHTS  |  {period}",
            f"  Template : {self.template_used}  |  Model : {self.model}",
            f"  Tokens   : {self.total_tokens:,}  |  Latency : {self.latency_ms:.0f}ms",
        ]
        if self.is_dry_run:
            header.append("  ⚠  DRY RUN — no real API call was made")
        if self.was_truncated:
            header.append("  ⚠  Response was truncated (max_tokens reached)")
        header.append(divider)

        print("\n".join(header))
        print(f"\n{self.insights_text}\n")
        print(divider)

    def __repr__(self) -> str:
        return (
            f"InsightReport(template={self.template_used!r}, "
            f"model={self.model!r}, tokens={self.total_tokens}, "
            f"dry_run={self.is_dry_run})"
        )


# ── InsightGenerator ──────────────────────────────────────────────────────────

class InsightGenerator:
    """Orchestrates PromptBuilder and LLMClient to produce an InsightReport.

    Parameters
    ----------
    client : LLMClient, optional
        Pre-configured LLM client.  If omitted, a default client is created
        using settings from ``config/settings.py``.
    builder : PromptBuilder, optional
        Pre-configured prompt builder.  If omitted, a default builder is
        created with standard settings.
    dry_run : bool, optional
        If True, skip the API call and return a placeholder report.
        Useful for testing the full pipeline locally.  Defaults to False.

    Examples
    --------
    >>> # Standard usage
    >>> generator = InsightGenerator()
    >>> report = generator.generate(result, template="recommendations")
    >>> report.print_cli()

    >>> # Dry run (no API key needed)
    >>> generator = InsightGenerator(dry_run=True)
    >>> report = generator.generate(result)
    >>> print(report.insights_text)
    """

    def __init__(
        self,
        client:  Optional[LLMClient]  = None,
        builder: Optional[PromptBuilder] = None,
        dry_run: bool = False,
    ) -> None:
        self.client  = client  or LLMClient()
        self.builder = builder or PromptBuilder()
        self.dry_run = dry_run

    # ------------------------------------------------------------------ #
    # Public API                                                          #
    # ------------------------------------------------------------------ #

    def generate(
        self,
        result:   AnalysisResult,
        template: str = "full_report",
    ) -> InsightReport:
        """Generate AI-powered insights from an AnalysisResult.

        Parameters
        ----------
        result : AnalysisResult
            Output of ``SalesAnalyzer.analyze()``.
        template : str
            Prompt template to use.  One of: ``"full_report"``,
            ``"executive_summary"``, ``"recommendations"``, ``"anomalies"``.

        Returns
        -------
        InsightReport

        Raises
        ------
        LLMClientError
            If the API call fails after all retries (non-dry-run mode only).
        ValueError
            If ``template`` is not a recognised template name.
        """
        print(
            f"[InsightGenerator] Building prompt "
            f"(template='{template}')..."
        )
        payload = self.builder.build(result, template=template)
        print(
            f"[InsightGenerator] Prompt ready — "
            f"~{payload.estimated_tokens:,} estimated tokens"
        )

        if self.dry_run:
            return self._dry_run_report(payload, result, template)

        if not self.client.validate():
            raise LLMClientError(
                "Cannot generate insights: OpenAI API key is not configured. "
                "Set OPENAI_API_KEY in your .env file, or use dry_run=True."
            )

        print(
            f"[InsightGenerator] Calling OpenAI API "
            f"(model={self.client.model!r})..."
        )
        llm_response = self.client.complete(
            system_prompt = payload.system,
            user_prompt   = payload.user,
        )

        print(
            f"[InsightGenerator] Done — "
            f"{llm_response.total_tokens:,} tokens used, "
            f"{llm_response.latency_ms:.0f}ms"
        )

        if llm_response.was_truncated:
            print(
                "[InsightGenerator] ⚠  Response was truncated. "
                "Consider increasing max_tokens in config/settings.py."
            )

        return InsightReport(
            insights_text     = llm_response.content,
            template_used     = template,
            model             = llm_response.model,
            prompt_tokens     = llm_response.prompt_tokens,
            completion_tokens = llm_response.completion_tokens,
            total_tokens      = llm_response.total_tokens,
            latency_ms        = llm_response.latency_ms,
            analysis_period   = result.date_range,
            row_count         = result.row_count,
            was_truncated     = llm_response.was_truncated,
            is_dry_run        = False,
        )

    # ------------------------------------------------------------------ #
    # Dry-run helper                                                      #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _dry_run_report(
        payload: PromptPayload,
        result:  AnalysisResult,
        template: str,
    ) -> InsightReport:
        """Return a placeholder report without calling the API."""
        placeholder = (
            "[DRY RUN — no API call was made]\n\n"
            "This is a placeholder for the AI-generated insights.\n\n"
            "In a live run, the model would receive the following prompt context "
            f"(~{payload.estimated_tokens:,} estimated tokens) and generate a "
            f"'{template}' analysis.\n\n"
            "To enable real AI insights:\n"
            "  1. Set OPENAI_API_KEY in your .env file\n"
            "  2. Run InsightGenerator(dry_run=False)\n\n"
            "--- PROMPT PREVIEW (first 600 chars of user message) ---\n"
            f"{payload.user[:600]}..."
        )

        return InsightReport(
            insights_text   = placeholder,
            template_used   = template,
            model           = "dry-run",
            analysis_period = result.date_range,
            row_count       = result.row_count,
            is_dry_run      = True,
        )

    def __repr__(self) -> str:
        return (
            f"InsightGenerator(model={self.client.model!r}, "
            f"dry_run={self.dry_run})"
        )
