"""
LLMClient — a thin, production-grade wrapper around the OpenAI Chat API.

Design decisions
----------------
1. **Thin wrapper, not an abstraction.**  This class does not try to be a
   provider-agnostic LLM interface.  It wraps OpenAI specifically but is
   small enough to be swapped or subclassed in < 30 minutes if needed.

2. **Structured response.**  The raw OpenAI response is unpacked into a
   clean ``LLMResponse`` dataclass so the rest of the pipeline never
   imports from ``openai`` directly — only this module does.

3. **Retry with exponential backoff.**  Rate-limit errors (429) and
   transient network failures are retried automatically up to
   ``max_retries`` times with doubling wait times.

4. **Token tracking.**  Usage (prompt + completion tokens) is recorded on
   every response for cost monitoring and audit trails.

5. **Graceful key validation.**  ``validate()`` checks for a set API key
   before any call is made, with a clear message pointing to the .env file.

Usage
-----
    client = LLMClient()
    if client.validate():
        response = client.complete(system_prompt, user_prompt)
        print(response.content)
        print(f"Tokens used: {response.total_tokens}")
"""

import os
import time
from dataclasses import dataclass

from config.settings import OPENAI_API_KEY, OPENAI_MODEL, OPENAI_MAX_TOKENS


@dataclass
class LLMResponse:
    """Structured result from a single LLM completion call.

    Attributes
    ----------
    content : str
        The text generated by the model.
    model : str
        The model that produced this response (as reported by the API).
    prompt_tokens : int
        Tokens consumed by the input (system + user messages).
    completion_tokens : int
        Tokens in the generated response.
    total_tokens : int
        prompt_tokens + completion_tokens.
    finish_reason : str
        Why generation stopped (``"stop"``, ``"length"``, ``"content_filter"``).
    latency_ms : float
        Wall-clock time of the API call in milliseconds.
    """

    content:           str
    model:             str
    prompt_tokens:     int
    completion_tokens: int
    total_tokens:      int
    finish_reason:     str
    latency_ms:        float

    @property
    def was_truncated(self) -> bool:
        """True if the response was cut off due to ``max_tokens``."""
        return self.finish_reason == "length"

    def __repr__(self) -> str:
        return (
            f"LLMResponse(model={self.model!r}, tokens={self.total_tokens}, "
            f"latency={self.latency_ms:.0f}ms, finish={self.finish_reason!r})"
        )


class LLMClient:
    """Sends chat completion requests to the OpenAI API.

    Parameters
    ----------
    api_key : str, optional
        OpenAI API key.  Defaults to the value from ``config/settings.py``
        (which reads ``OPENAI_API_KEY`` from the environment / .env file).
    model : str, optional
        Model identifier.  Defaults to ``OPENAI_MODEL`` from settings.
    max_tokens : int, optional
        Maximum tokens to generate.  Defaults to ``OPENAI_MAX_TOKENS``.
    temperature : float, optional
        Sampling temperature.  0.0 = deterministic, 1.0 = creative.
        Defaults to ``0.4`` — low enough for factual analysis, high enough
        to avoid robotic repetition.
    max_retries : int, optional
        Number of retry attempts on rate-limit / transient errors.
        Defaults to 3.

    Examples
    --------
    >>> client = LLMClient()
    >>> if client.validate():
    ...     response = client.complete(system, user)
    ...     print(response.content)
    """

    def __init__(
        self,
        api_key:     str   = "",
        model:       str   = OPENAI_MODEL,
        max_tokens:  int   = OPENAI_MAX_TOKENS,
        temperature: float = 0.4,
        max_retries: int   = 3,
    ) -> None:
        # Read the key fresh from the environment at instantiation time so
        # load_dotenv() calls that happen after module import are honoured.
        self.api_key     = api_key or os.getenv("OPENAI_API_KEY", "")
        self.model       = model
        self.max_tokens  = max_tokens
        self.temperature = temperature
        self.max_retries = max_retries
        self._client     = None  # initialised lazily on first use

    # ------------------------------------------------------------------ #
    # Public API                                                          #
    # ------------------------------------------------------------------ #

    def validate(self) -> bool:
        """Return True if an API key is configured.

        Does NOT make an API call — just checks that a non-empty key exists.
        Call this before ``complete()`` to give the user a clear error message
        rather than a cryptic 401 from the API.
        """
        if not self.api_key or self.api_key.startswith("sk-..."):
            print(
                "[LLMClient] No OpenAI API key configured.\n"
                "  → Copy .env.example to .env and set OPENAI_API_KEY."
            )
            return False
        return True

    def complete(
        self,
        system_prompt: str,
        user_prompt:   str,
    ) -> LLMResponse:
        """Send a chat completion request and return a structured response.

        Parameters
        ----------
        system_prompt : str
            The system message (role definition, instructions).
        user_prompt : str
            The user message (data context + task).

        Returns
        -------
        LLMResponse

        Raises
        ------
        LLMClientError
            If the API call fails after all retries.
        """
        self._ensure_client()
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ]

        last_error: Exception | None = None

        for attempt in range(1, self.max_retries + 1):
            try:
                return self._call_api(messages)

            except Exception as exc:
                last_error = exc
                error_str  = str(exc).lower()

                # Rate limit or server overload — retry with backoff
                if any(code in error_str for code in ("429", "rate_limit", "overload", "500", "503")):
                    wait = 2 ** attempt  # 2s, 4s, 8s
                    print(
                        f"[LLMClient] Attempt {attempt}/{self.max_retries} failed "
                        f"({type(exc).__name__}). Retrying in {wait}s..."
                    )
                    time.sleep(wait)
                    continue

                # Non-retryable error (auth, bad request, etc.) — fail immediately
                raise LLMClientError(
                    f"OpenAI API call failed: {exc}"
                ) from exc

        raise LLMClientError(
            f"OpenAI API call failed after {self.max_retries} retries. "
            f"Last error: {last_error}"
        )

    # ------------------------------------------------------------------ #
    # Internal helpers                                                    #
    # ------------------------------------------------------------------ #

    def _ensure_client(self) -> None:
        """Lazily initialise the OpenAI client."""
        if self._client is not None:
            return
        try:
            from openai import OpenAI
        except ImportError as exc:
            raise LLMClientError(
                "The 'openai' package is not installed. "
                "Run:  pip install openai"
            ) from exc

        self._client = OpenAI(api_key=self.api_key)

    def _call_api(self, messages: list) -> LLMResponse:
        """Execute the API call and unpack the response into LLMResponse."""
        t_start = time.monotonic()

        response = self._client.chat.completions.create(
            model       = self.model,
            messages    = messages,
            max_tokens  = self.max_tokens,
            temperature = self.temperature,
        )

        latency_ms = (time.monotonic() - t_start) * 1000
        choice     = response.choices[0]
        usage      = response.usage

        return LLMResponse(
            content           = choice.message.content or "",
            model             = response.model,
            prompt_tokens     = usage.prompt_tokens,
            completion_tokens = usage.completion_tokens,
            total_tokens      = usage.total_tokens,
            finish_reason     = choice.finish_reason or "unknown",
            latency_ms        = round(latency_ms, 1),
        )

    def __repr__(self) -> str:
        key_preview = f"{self.api_key[:8]}..." if self.api_key else "not set"
        return (
            f"LLMClient(model={self.model!r}, "
            f"max_tokens={self.max_tokens}, "
            f"temperature={self.temperature}, "
            f"key={key_preview})"
        )


class LLMClientError(Exception):
    """Raised when the LLM API call fails unrecoverably."""
